version: "3.8"
services:
  warehouse-app:
    build: .
    image: warehouse-app
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
