version: '3.8'
services:
  warehouse-app:
    container_name: warehouse-app-prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=production
    command: npm start
