version: "3.8"
services:
  warehouse-app:
    container_name: warehouse-app-dev
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn dev
